Repository vabold/Kinoko, pull requests merged in 2024-12, with the labels that each got.

#166 Sync zipper mid-air physics
  STATUS.md
  source/egg/math/Math.hh
  source/game/field/KCollisionTypes.hh
  source/game/kart/KartCollide.cc
  source/game/kart/KartHalfPipe.cc
  source/game/kart/KartHalfPipe.hh
  source/game/kart/KartMove.cc
  source/game/kart/KartMove.hh
  source/game/kart/KartObjectProxy.cc
  source/game/kart/KartObjectProxy.hh
  source/game/kart/KartState.cc
  source/game/kart/KartState.hh
  source/game/kart/KartSub.cc
Labels: P3

#194 Implement start boost burnout
  source/game/item/KartItem.cc
  source/game/kart/KartBurnout.cc
  source/game/kart/KartBurnout.hh
  source/game/kart/KartMove.cc
  source/game/kart/KartMove.hh
  source/game/kart/KartState.cc
  source/game/kart/KartState.hh
Labels: P1

#195 Error on implicit float-to-double promotion
  configure.py
  source/egg/core/Heap.cc
  source/egg/math/Math.cc
  source/game/field/ObjectCollisionBase.cc
  source/game/kart/KartHalfPipe.cc
Labels: improvement, P4

#179 Add cmake build generator
  CMakeLists.txt
  README.md
  tools/generate_tests.py
Labels: P3

#196 Create a Discord bot
  .gitignore
  tools/discord/bot.py
Labels: scripting, P2

#197 Implement checkpoint calculation
  source/game/scene/RaceScene.cc
  source/game/system/CourseMap.cc
  source/game/system/CourseMap.hh
  source/game/system/RaceManager.cc
  source/game/system/RaceManager.hh
  source/game/system/map/MapdataCheckPath.cc
  source/game/system/map/MapdataCheckPath.hh
  source/game/system/map/MapdataCheckPoint.cc
  source/game/system/map/MapdataCheckPoint.hh
Labels: P1

#119 Rename asset folder
  source/game/system/ResourceManager.cc
Labels: P3

#200 Sync respawns and landing boosts
  STATUS.md
  source/game/kart/KartCollide.cc
  source/game/kart/KartDynamics.cc
  source/game/kart/KartDynamics.hh
  source/game/kart/KartMove.cc
  source/game/kart/KartMove.hh
  source/game/kart/KartObjectProxy.cc
  source/game/kart/KartObjectProxy.hh
  source/game/kart/KartState.cc
  source/game/kart/KartState.hh
  source/game/kart/KartSub.cc
  source/game/kart/KartSuspensionPhysics.cc
  source/game/system/CourseMap.cc
  source/game/system/CourseMap.hh
  source/game/system/RaceManager.cc
  source/game/system/RaceManager.hh
Labels: P1

#204 Add initial timer support
  source/egg/math/Vector.hh
  source/game/system/CourseMap.cc
  source/game/system/CourseMap.hh
  source/game/system/GhostFile.hh
  source/game/system/RaceManager.cc
  source/game/system/RaceManager.hh
  source/game/system/Timer.cc
  source/game/system/Timer.hh
  source/game/system/TimerManager.cc
  source/game/system/TimerManager.hh
  source/game/system/map/MapdataCheckPoint.cc
  source/game/system/map/MapdataCheckPoint.hh
Labels: P1

#207 Implement auto drifting
  source/game/kart/KartMove.cc
  source/game/kart/KartMove.hh
  source/game/kart/KartPhysics.cc
  source/game/kart/KartPhysics.hh
  source/game/kart/KartState.cc
  source/game/kart/KartState.hh
Labels: P1

#209 Fix wall collision speed factor bug
  source/game/kart/KartMove.cc
Labels: P1

#210 Fix auto drift having wrong rotation sign
  source/game/kart/KartMove.cc
Labels: P1

#211 Fix SSMT canceling
  source/game/kart/KartMove.cc
  source/game/kart/KartState.cc
  source/game/kart/KartState.hh
Labels: P1

#206 Add a replay system
  source/game/system/GhostFile.cc
  source/game/system/GhostFile.hh
  source/game/system/RaceManager.cc
  source/game/system/RaceManager.hh
  source/game/system/TimerManager.cc
  source/game/system/TimerManager.hh
  source/host/KReplaySystem.cc
  source/host/KReplaySystem.hh
  source/host/Option.cc
  source/host/Option.hh
  source/host/main.cc
Labels: P1

#218 Update lapCompletion
  source/game/system/RaceManager.cc
Labels: P1

#219 Add missing burnout rotation handling
  source/game/kart/KartBody.cc
  source/game/kart/KartBurnout.cc
  source/game/kart/KartBurnout.hh
  source/game/render/KartModel.cc
  source/game/render/KartModel.hh
Labels: P1

#220 Add ghost replay to Discord bot
  tools/discord/bot.py
Labels: P2

#223 Add missing 0 distance check
  source/game/field/KColData.cc
Labels: P1
